# Site settings
title: Psyche i Logos
email: youremailaddress@gmail.com
description: Strona internetowa Studenckiego Ko≈Ça Naukowego Psyche i Logos
baseurl: "/WebsitePsycheILogos" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
plugins: [jekyll-paginate]

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Pagination
paginate: 8
paginate_path: "/blog/page:num/"

# Social settings
500px_url:
facebook_url: https://www.facebook.com/SKNPsycheLogos/
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/sknpsychelogos/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
